Now request params is a plain string
CartoDB/cartodb-common pull request #9
Opened 2020-09-02 15:47 UTC by thedae

2020-09-02 16:18 UTC, amiedes requested changes
I've just left a minor comment 🙂

2020-09-02 16:18 UTC, amiedes commented on lib/carto/common/rack_logger_middleware.rb
> +            hash[key] = value.join(',')
If the value was something like `["personal_info_1", "personal_info_2"]` would't we be sending it to the logs in plain as `personal_info_1, personal_info_2`?

I think we should obfuscate it also if it's not a `LOGGABLE_PARAMS `

2020-09-02 16:24 UTC, thedae commented on lib/carto/common/rack_logger_middleware.rb
> +            hash[key] = value.join(',')
Before these changes the key-pair of an array was something like:
```
key1=value1&key2="Instance of Array"
```
which looked weird, that's why I added these lines.

Anyway, you're right, this value should be obfuscated, I'm on it!

2020-09-03 09:14 UTC, amiedes commented on lib/carto/common/rack_logger_middleware.rb
> +            hash[key] = value.map { |entry| obfuscate_string(entry) }.join(",")
Just for you to know, in Ruby you can also summarise:

```ruby
value.map { |entry| obfuscate_string(entry) }.join(",")
```

as:

```ruby
value.map(&:obfuscate_string).join(",")
```

But no need to change it 🙂

2020-09-03 09:14 UTC, amiedes approved these changes
Nice work, thanks for taking care of this 🙏

2020-09-03 11:29 UTC, merged